image:
  name: andrewgoacher/rust-nightly-goachdev:latest
  entrypoint: [""]

stages:
  - build
  - deploy

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo

before_script:
  - apt install openssh-client bash
  - chmod +x ./setup_env.sh
  - bash ./setup_env.sh

build:
  stage: build
  only:
    refs:
      - master
  script:
    - echo "building thegoach.dev"
    - cargo build --release
  cache:
    paths:
      - target/
      - cargo/

deploy:
  stage: deploy
  only:
    refs:
      - master
  script:
    - mkdir -p ~/.ssh
    - echo "$PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - cat ~/.ssh/id_rsa
    - chmod 700 ~/.ssh/id_rsa
    - eval "$(ssh-agent -s)"
    - ssh-add ~/.ssh/id_rsa
    - ssh-keyscan -H 'gitlab.com' >> ~/.ssh/known_hosts
    - chmod +x ./deploy.sh
    - echo "Hello"
    - ls
    - scp  -o StrictHostKeyChecking=no -r ./.env ./docker-compose.yml ./data/ ./public/ ./templates/ ./Rocket.toml ./target/release/thegoach_dev $SSH_USER@$DIGITAL_OCEAN_IP_ADDRESS:/app_new
    - bash ./deploy.sh