version: '2'

services:
  app:
    image: registry.gitlab.com/andrewgoacher/thegoach.dev:web
    environment:
      ROCKET_ENV: ${ROCKET_ENV}
  https-portal:
    image: steveltn/https-portal:1
    volumes:
      - /data/ssl_certs:/var/lib/https-portal
    ports:
      - '80:80'
      - '443:443'
    links:
      - app
    restart: always
    environment:
      DOMAINS: 'thegoach.dev -> http://app:8000, www.thegoach.dev => thegoach.dev'
