version: '2'

services:
  https-portal:
    image: steveltn/https-portal:1
    volumes:
      - /data/ssl_certs:/var/lib/https-portal
    ports:
      - '80:80'
      - '443:443'
    links:
      - app
    restart: always
    environment:
      STAGE: 'production'
      DOMAINS: 'thegoach.dev -> http://dockerhost:8000, www.thegoach.dev => thegoach.dev'
