version: '2'

services:
  app:
    image: registry.gitlab.com/andrewgoacher/thegoach.dev/website
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - app
    restart: always
    environment:
      DOMAINS: 'andrewgoacher.com -> http://app:8000, thegoach.dev -> http://app:8000' # www.andrewgoacher.com => andrewgoacher.com, thegoach.dev -> http://app:8000, www.thegoach.dev => thegoach.dev'
      STAGE: ${THEGOACH_STAGE}
      ROCKET_ENV: ${THEGOACH_STAGE}
